version: '3'
services:
    prometheus:
        image: 'prom/prometheus:v2.1.0'
        container_name: prometheus
        restart: always
        ports:
            - '9090:9090'
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        volumes:
            - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
            # - './alert.rules:/etc/prometheus/alert.rules'
        depends_on:
            - cadvisor
        networks:
            - samplenet    
            
    grafana_server:
        image: grafana/grafana:6.5.0
        restart: always
        ports:
            - '3001:3000'
        container_name: grafana_server
        networks:
            - samplenet
 
    cadvisor:
        image: google/cadvisor
        restart: always
        container_name: cadvisor
        ports:
            - '8020:8080'
        volumes:
            - '/:/rootfs:ro'
            - '/var/run:/var/run:rw'
            - '/sys:/sys:ro'
            - '/var/lib/docker/:/var/lib/docker:ro'
        networks:
            - samplenet
    # alertmanager:
    #     image: prom/alertmanager
    #     ports:
    #         - '9093:9093'
    #     volumes:
    #         - './alertmanager/config.yml:/etc/alertmanager/config.yml'
    #     restart: always
    #     command:
    #         - '--config.file=/etc/alertmanager/config.yml'
    #         - '--storage.path=/alertmanager'
    #     networks:
    #         - samplenet
    node-exporter:
        image: prom/node-exporter
        volumes:
            - '/proc:/host/proc:ro'
            - '/sys:/host/sys:ro'
            - '/:/rootfs:ro'
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points'
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - '9100:9100'
        networks:
            - samplenet
        restart: always
volumes:
    prometheus_data: {}

networks:
  samplenet:

